# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 337f7bfe2df0304bc87283dd6c2e699d1d74de41dbf00f084a3f25dcbae70ba6405dc28091d9951559f071ca487d3b82b8eb4a25aff489e763aad77cbcfa46da

test:
  secret_key_base: 79ec7a8424fba7367fbb21febf4d3f6d5a5bd3718056394f425c920292b4d4b5bd1f3705f29eba7dc543032dccc9613d9b53bde1a0ce7937b61fb0e4f1aa9efe

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
